#!/bin/bash
# Claude-ProjectでMCP Gatewayをセットアップするためのコマンド集

echo "📋 以下のコマンドを順番に実行してください:"
echo ""
echo "# 1. Claude-Projectディレクトリに移動"
echo "cd ~/Claude-Project"
echo ""
echo "# 2. セットアップスクリプトを実行"
echo "./setup-gateway.sh"
echo ""
echo "# 3. または、手動でセットアップする場合:"
echo ""
echo "# Git Submoduleとして追加"
echo "git submodule add https://github.com/kirinnokubinagai/mcp-gateway.git mcp-gateway"
echo ""
echo "# 依存関係をインストール"
echo "cd mcp-gateway && bun install && cd .."
echo ""
echo "# 4. プロキシサーバーを起動（新しいターミナルで）"
echo "./start-gateway-proxy.sh"
echo ""
echo "# 5. Docker環境を起動（別のターミナルで）"
echo "docker compose -f docker-compose-base.yml -f docker-compose.gateway.yml up -d"
echo ""
echo "# 6. コンテナに接続してMCP設定を切り替え"
echo "docker exec -it claude-code-\${PROJECT_NAME} bash"
echo "setup-mcp-gateway"
echo ""
echo "# 7. 動作確認"
echo "ccd  # Claude CLIでMCPツールが使えることを確認"
echo ""
echo "📌 アクセス先:"
echo "- MCP管理用Web UI: http://localhost:3002"
echo "- MCP Gateway API: http://localhost:3003"